FROM resin/%%RESIN_MACHINE_NAME%%-openjdk

MAINTAINER Ed Sweeney <ed@onextent.com>

RUN apt-get update && \
    apt-get -y install git sbt && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

RUN git clone https://github.com/navicore/mqtt-bridge.git && cd mqtt-bridge && sbt assembly

RUN mkdir -p /app

#COPY lib/*.jar /app/
RUN cp mqtt-bridge/target/scala-2.12//*.jar /app/

WORKDIR /app

CMD ["java","-jar","/app/MqttBridge.jar"]

# TODO: multistage dockerfile
