version: '2'
volumes: 
  mqtt-data:
services:
  mqtt-broker:
    build: ./mqtt-broker
    expose:
      - "1883"
      - "9001"
    privileged: true
    restart: always
    network_mode: host
    volumes: 
      - "mqtt-data:/mqtt/data"
  mqtt-bridge:
    build: ./mqtt-bridge
    privileged: true
    depends_on:
      - mqtt-broker
    restart: always
    network_mode: host
