version: '2'
services:
  mqtt-broker:
    build: ./mqtt-broker
    expose:
      - "1993"
      - "9001"
    privileged: true
    restart: always
    network_mode: host
  amqp-bridge:
    links:
      - mqtt-broker
    build: ./mqtt-bridge
    depends_on:
      - mqtt-broker
