version: '2'
services:
  mqtt-broker:
    build: ./mqtt-broker
    expose:
      - "1883"
      - "9001"
    privileged: true
    restart: always
    network_mode: host
    networks:
      svcnet:
        aliases:
          - mqtt-broker
  mqtt-bridge:
    build: ./mqtt-bridge
    depends_on:
      - mqtt-broker
    restart: always
    network_mode: host
    networks:
      svcnet:
        aliases:
          - mqtt-bridge
networks:
  svcnet:
